apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: elk
  name: elk
spec:
  ports:
  - name: "5601"
    port: 5601
    targetPort: 5601
  - name: "9200"
    port: 9200
    targetPort: 9200
  - name: "5044"
    port: 5044
    targetPort: 5044
  - name: "9300"
    port: 9300
    targetPort: 9300
  selector:
    io.kompose.service: elk
status:
  loadBalancer: {}
