apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: elk
  name: elk
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: elk
    spec:
      containers:
      - env:
        - name: INICIAR_FILEBEAT
          value: /opt/logstash/bin/logstash --path.data /tmp/logstash/data \-e 'input { stdin { } } output { elasticsearch { hosts => ["localhost"] } }'
        image: angel85/stack-elk
        name: elk
        ports:
        - containerPort: 5601
        - containerPort: 9200
        - containerPort: 5044
        - containerPort: 9300
        resources: {}
      restartPolicy: Always
status: {}
